import type { KnowledgePack } from "@/lib/knowledge/types";

export const KNOWLEDGE_PACK_VERSION = "1.0.0";

export const knowledgePackV1: KnowledgePack = {
  version: KNOWLEDGE_PACK_VERSION,
  publishedAt: "2026-06-25",
  articles: [
    {
      id: "pda-demand-language",
      domain: "pda",
      title: "Reduce perceived demands",
      summary: "PDA profiles often experience ordinary requests as threats when demand language is direct.",
      guidance: [
        "Use declarative language instead of commands.",
        "Offer indirect choices between two acceptable options.",
        "Allow recovery time before revisiting a request.",
      ],
      tags: ["pda", "demand", "transition", "school"],
      evidenceLevel: "widely_recommended",
      version: KNOWLEDGE_PACK_VERSION,
    },
    {
      id: "pda-recovery",
      domain: "pda",
      title: "Recovery after overwhelm",
      summary: "After a meltdown or shutdown, the nervous system needs safety before learning can resume.",
      guidance: [
        "Reduce all non-essential demands for at least 30–60 minutes.",
        "Stay nearby without requiring eye contact or explanation.",
        "Reintroduce structure gently with visual supports.",
      ],
      tags: ["pda", "meltdown", "recovery", "regulation"],
      evidenceLevel: "widely_recommended",
      version: KNOWLEDGE_PACK_VERSION,
    },
    {
      id: "autism-predictability",
      domain: "autism",
      title: "Predictability supports regulation",
      summary: "Unexpected changes increase cognitive load and anxiety for many autistic children.",
      guidance: [
        "Give advance notice before transitions.",
        "Use visual schedules for mornings and after-school.",
        "Prepare for changes with social stories when possible.",
      ],
      tags: ["autism", "transition", "routine", "school"],
      evidenceLevel: "established",
      version: KNOWLEDGE_PACK_VERSION,
    },
    {
      id: "autism-sensory",
      domain: "sensory",
      title: "Sensory regulation",
      summary: "Sensory overload is a neurological response, not behavioural choice.",
      guidance: [
        "Reduce sensory input before adding demands.",
        "Offer ear defenders, sunglasses, or a quiet space.",
        "Plan exit strategies for busy environments.",
      ],
      tags: ["sensory", "autism", "shopping", "crowd"],
      evidenceLevel: "established",
      version: KNOWLEDGE_PACK_VERSION,
    },
    {
      id: "adhd-movement",
      domain: "adhd",
      title: "Movement supports focus",
      summary: "Movement breaks can improve attention and demand tolerance for many ADHD profiles.",
      guidance: [
        "Build short movement breaks into homework and mornings.",
        "Break tasks into small, achievable steps.",
        "Use timers and visual progress markers.",
      ],
      tags: ["adhd", "homework", "energy", "school"],
      evidenceLevel: "widely_recommended",
      version: KNOWLEDGE_PACK_VERSION,
    },
    {
      id: "adhd-executive-function",
      domain: "executive_function",
      title: "Executive function scaffolding",
      summary: "Starting, switching, and finishing tasks require extra support when executive function is immature or overloaded.",
      guidance: [
        "Co-regulate before expecting independent task completion.",
        "Use first-then language paired with visuals.",
        "Celebrate initiation, not only completion.",
      ],
      tags: ["adhd", "executive_function", "homework", "transition"],
      evidenceLevel: "widely_recommended",
      version: KNOWLEDGE_PACK_VERSION,
    },
    {
      id: "anxiety-validation",
      domain: "anxiety",
      title: "Validate before problem-solving",
      summary: "Anxiety reduces capacity for cooperation; safety must come before correction.",
      guidance: [
        "Name the feeling without minimising it.",
        "Lower expectations temporarily during high anxiety.",
        "Avoid reassurance loops that become new demands.",
      ],
      tags: ["anxiety", "school", "refusal", "morning"],
      evidenceLevel: "established",
      version: KNOWLEDGE_PACK_VERSION,
    },
    {
      id: "sleep-regulation",
      domain: "parenting",
      title: "Sleep and next-day capacity",
      summary: "Poor sleep commonly reduces tolerance for demands, transitions, and sensory input the following day.",
      guidance: [
        "Prioritise consistent bedtime routines on school nights.",
        "Keep mornings low-demand after disrupted sleep.",
        "Track sleep alongside mood and school ratings.",
      ],
      tags: ["sleep", "school", "morning", "regulation"],
      evidenceLevel: "established",
      version: KNOWLEDGE_PACK_VERSION,
    },
    {
      id: "school-accommodations",
      domain: "school_accommodations",
      title: "Classroom accommodations",
      summary: "Small environmental adjustments often prevent escalation at school.",
      guidance: [
        "Provide a quiet break space without stigma.",
        "Use reduced demand language from all staff.",
        "Allow movement breaks and flexible seating.",
        "Share predictable transition warnings.",
      ],
      tags: ["school", "teacher", "accommodations", "sensory"],
      evidenceLevel: "established",
      version: KNOWLEDGE_PACK_VERSION,
    },
    {
      id: "homework-decompression",
      domain: "school_accommodations",
      title: "After-school decompression",
      summary: "Many children need recovery time between school and homework demands.",
      guidance: [
        "Allow 30–60 minutes of regulation before homework.",
        "Offer snacks, movement, or quiet time first.",
        "Reduce homework battles on already difficult days.",
      ],
      tags: ["homework", "school", "anxiety", "adhd"],
      evidenceLevel: "widely_recommended",
      version: KNOWLEDGE_PACK_VERSION,
    },
    {
      id: "visitor-transitions",
      domain: "parenting",
      title: "Visitors and routine disruption",
      summary: "Social visitors change the sensory and social environment of the home.",
      guidance: [
        "Prepare your child in advance when visitors are expected.",
        "Designate a quiet retreat space.",
        "Keep visits shorter on already demanding days.",
      ],
      tags: ["visitor", "anxiety", "transition", "home"],
      evidenceLevel: "contextual",
      version: KNOWLEDGE_PACK_VERSION,
    },
    {
      id: "professional-boundaries",
      domain: "professional",
      title: "When to seek professional support",
      summary: "Parents should not carry safety concerns alone.",
      guidance: [
        "Contact your GP, paediatrician, or crisis support if anyone's safety is at risk.",
        "Persistent patterns affecting daily life warrant professional discussion.",
        "Reaching out is a sign of care, not failure.",
      ],
      tags: ["professional", "safety", "support"],
      evidenceLevel: "established",
      version: KNOWLEDGE_PACK_VERSION,
    },
  ],
};
