export const aiCopy = {
  intelligenceHeading: "Here's what I've noticed",
  intelligenceSub: "Gentle signals from your days together — tap \"Why?\" if you'd like to understand more.",
  briefingIntro: "Here's your calm snapshot for today.",
  reportCreating: "Getting your summary ready…",
  reportReady: "Your summary is ready to view.",
  checkinSaved: "Today's check-in is saved. You're doing beautifully.",
  debriefThinking: "I'm reflecting on what you shared…",
  coachThinking: "I'm thinking about what you shared…",
  uploadSuccess: "Saved safely with your family.",
  saveSuccess: "Saved — your changes are safe with us.",
  supportReceived: "Thank you — we've received your message and will respond soon.",
} as const;

export const actionCopy = {
  saveCheckin: "Save today's check-in",
  createReport: "Create a Summary",
  previewReport: "View",
  freshReport: "Create a Fresh Copy",
  exportPdf: "Share",
  addChild: "Add your child",
  inviteCaregiver: "Invite a caregiver",
  saveProfile: "Save my profile",
  saveFamily: "Save family details",
  saveObservation: "Save this note",
  getGuidance: "Talk it through together",
  sendMessage: "Share what's on your mind",
  continue: "Let's keep going together",
  goBack: "Go back",
} as const;
